# -*- coding: utf-8 -*-
"""DLLAB2_178.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BO6965S5meP1GXeYjuCZrly8dam36qmY
"""

# Single input data
X = [0, 1, 2, 3]

# Target output
Y = 1

# Initialize weight
w = 0.5

# Initialize bias
b = -0.5

# Learning rate
eta = 0.1

# Number of epochs
epochs = 10

def net_input(x, w, b):
    return (w * x) + b

def activation(z):
    if z >= 0:
        return 1
    else:
        return 0

def error(y, y_pred):
    return y - y_pred

def update_weight(w, x, err, eta):
    return w + eta * err * x

def update_bias(b, err, eta):
    return b + eta * err

for epoch in range(epochs):
    print(f"\nEpoch {epoch + 1}")

    for i in range(len(X)):
        # Step 2
        z = net_input(X[i], w, b)

        # Step 3
        y_pred = activation(z)

        # Step 4
        err = error(Y, y_pred)

        if err == 0:
            print(f"x={X[i]} → Correct prediction ({y_pred})")
        else:
            # Step 5 & 6
            w = update_weight(w, X[i], err, eta)
            b = update_bias(b, err, eta)

            print(f"x={X[i]} → Error={err}")
            print(f"Updated weight: {w}")
            print(f"Updated bias: {b}")

print("\nFinal Model")
print("Weights:", W)
print("Bias:", b)

